import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: "#F5F9FF" },
  loaderContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 20,
    backgroundColor: "#1E3A8A",
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
  },
  modalCenteredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  addCategoryModal: {
    width: "80%",
    backgroundColor: "white",
    borderRadius: 15,
    padding: 20,
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", marginBottom: 15 },
  input: {
    borderBottomWidth: 1,
    borderBottomColor: "#CCC",
    marginBottom: 20,
    padding: 8,
  },
  modalButtons: { flexDirection: "row", justifyContent: "flex-end" },
  // choresHeader: {
  //   backgroundColor: "#FFF",
  //   paddingBottom: 20,
  //   paddingTop: 10,
  //   borderBottomWidth: 1,
  //   borderBottomColor: "#E0E0E0",
  // },
  calendarStrip: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 10,
  },
  dateCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#6295BE",
  },
  activeDate: { backgroundColor: "#1E3A8A", borderColor: "#1E3A8A" },
  dayText: { fontSize: 10, color: "#666" },
  dateText: { fontSize: 14, fontWeight: "bold", color: "#333" },
  activeText: { color: "#FFF" },
  cardContainer: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    marginBottom: 16,
    elevation: 4,
    overflow: "hidden",
  },
  choreItemRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#F9F9F9",
  },
  choreMainClick: { flexDirection: "row", alignItems: "center", flex: 1 },
  choreText: { marginLeft: 12, fontSize: 15, color: "#444" },
  completedText: { textDecorationLine: "line-through", color: "#AAA" },
  inlineAddContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 8,
  },
  inlineInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    color: "#333",
    height: 40,
  },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.1)" },
  menuContainer: {
    position: "absolute",
    right: 25,
    backgroundColor: "white",
    borderRadius: 12,
    width: 160,
    elevation: 15,
    padding: 4,
    borderWidth: 1,
    borderColor: "#EEE",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  emptyAddButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
    backgroundColor: "#FAFCFF",
  },
  emptyAddText: {
    marginLeft: 8,
    color: "#1E3A8A",
    fontSize: 14,
    fontWeight: "500",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 100, // Screen ke beech mein lane ke liye
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginTop: 20,
  },
  emptySubtitle: {
    fontSize: 14,
    color: "#777",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 30,
  },
  addFirstButton: {
    flexDirection: "row",
    backgroundColor: "#1E3A8A",
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 30,
    alignItems: "center",
    elevation: 3,
  },
  addFirstButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },
  smartCard: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 25,
    width: "100%",
    alignItems: "center",
    elevation: 4,
    shadowColor: "#1E3A8A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    borderWidth: 1,
    borderColor: "#E1E8F0",
  },
  smartCardIconBg: {
    backgroundColor: "#F0F4FF",
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
  },
  smartCardTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1E3A8A",
    marginBottom: 8,
  },
  smartCardSubtitle: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  smartSyncButton: {
    backgroundColor: "#1E3A8A",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
  },
  smartSyncButtonText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 15,
  },
  headerWrapper: {
    marginBottom: 15, // List items se thora fasla
  },
  smartBanner: {
    backgroundColor: "#EBF2FF", // Light blue background
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#D0E0FF",
    elevation: 2, // Thora sa shadow
  },
  smartBannerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  sparkleCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  bannerTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1E3A8A",
  },
  bannerSubtitle: {
    fontSize: 12,
    color: "#6295BE",
    marginTop: 1,
  },
  // Add to listStyles
  choresHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: "white",
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  choresListContent: {
    padding: 16,
    paddingBottom: 100,
  },
});
